### ISSUE TITLE
1.4.0 crashes during pip install (Ubuntu 16.04, Python 3.6.3)

### ISSUE THREAD

**Issue by Deimos** [jvanasco/pyramid_session_redis#10]
Hey @jvanasco,

Was just doing a routine update of my pypi packages, and the new version of pyramid-session-redis from earlier today seems to crash during install, looks like an encoding issue during trying to read in the README file. Here's the error/traceback from my log:

```
Collecting pyramid-session-redis (from -r /opt/something/requirements.txt (line 25))
  Downloading pyramid_session_redis-1.4.0.tar.gz (52kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yrbq14xv/pyramid-session-redis/setup.py", line 24, in <module>
        README = text_file.read()
      File "/usr/local/pyenv/versions/3.6.3/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 733: ordinal not in range(128)
```

**Comment by jvanasco** [comment]
Oh no. I'm sorry. I just upped this and that didn't catch on my tests.  I should run tests on another box.

Thanks for the report.  I"ll fix this tonight.  

FYI as per the new release notes, 1.4.x is a new branch that isn't entirely backwards compatible.  You can pin to <=1.3.0 (which will stay backwards compatible for 1.2.x).

**Comment by jvanasco** [comment]
i pulled 1.4.0 from pypi so this won't break anyone else.  you caught this fast. it's been 2 hours or so.

**Comment by Deimos** [comment]
No worries, thanks for continuing to work on the library. I usually just update all my packages once a week or so, so it was just very good (bad?) timing. And thanks for the note about backwards-compatibility, I'll take a look and see if anything should affect me (probably not, I'm not doing anything fancy).

**Comment by jvanasco** [comment]
`1.4.1` fix is out and I tested deploying it. Really sorry about that hiccup - I haven't touched this in 6 months and realized I should do another release after integrating the 'invalid logger' callback yesterday. I totally forgot to test Python3 -- we've been running the github master under Python27 since Feb.

Unless you were touching the internals, the only big difference I recall making between 1.2 and 1.4 is that the 1.4 payload format changed -- so existing sessions will be invalid.  

The old format was hardcoded to this:

    {'managed_dict': {},
     'created': INT,
     'timeout': INT,
     }

The new version streamlined the keys for a lighter footprint and generally looks like this:

    {'m': {},  # managed_dict
      'c': INT,  # created 
      'v': SESSION_API_VERSION,  # session INT
      # the following are optional and not guaranteed to be around
      't': INT,  # timeout, not gua
      'x': INT,  # expiry
      }

I thought about trying to read the old format as a fallback - but it didn't seem worth the work.

**Comment by Deimos** [comment]
Thanks, updated to 1.4.1 today and it worked perfectly. Didn't notice any impact at all, but like I said, I'm only using it in a very straightforward manner.
