### ISSUE TITLE
Document basic usage with login

### ISSUE THREAD

**Issue by hyperknot** [jvanasco/pyramid_session_redis#29]
I'm migrating from pyramid_redis_sessions, and I just wanted to confirm that I understand the basic usage correctly.

Basically all this is in ini:
```
secret = xxx
timeout = 1800
timeout_trigger = 900
cookie_max_age = 315360000  # 10 years
```

And in login endpoint: 
```
headers = remember(request, user.id)

redis_timeout = 3600 * 24 * 365  # one year in Redis
request.session.adjust_timeout_for_session(redis_timeout)

return HTTPFound(location=..., headers=headers)
```

Is this correct? Especially these are my concerns:
- Is it true that pyramid_session_redis, the remember() cannot take a max_age keyword, thus change the expiry time on an already set cookie? (Or set a new browser cookie?)
- I can just set all browser cookies, even non-logged-in users to a really large value, like 10 years in future and don't worry about it at all, since I'm taking care of all expiry times via Redis TTL functionality?

I'd like to have 1800 secs just for basic CSRF functionality and allow logged in users 1 years between subsequent logins. Is the above config correct for this usage?

One thing I'm not finding anywhere: how does timeout_trigger work in combination with adjust_timeout_for_session? Afaik adjust_timeout_for_session only sets timeout, but I'd need to change timeout_trigger to something like half of it as well. timeout = 31536000 with timeout_trigger = 900 doesn't really make any sense, does it?

In this case, should I revert to not using timeout_trigger?

**Comment by jvanasco** [comment]
You want:
```
secret = xxx
timeout = 1800
timeout_trigger = 900
cookie_max_age = 31536000  # 1 years
```

First- `timeout_trigger` is a feature that you may not need. It was designed to optimize read-heavy situations. If set, READ scenarios will not extend the timeout (which requires a WRITE by sending an EXPIRY to Redis) until this trigger value is met. This is accomplished by stashing some timeout data in the redis payload itself, and not just using the TTL values in redis. see [`encode_session_payload(`](https://github.com/jvanasco/pyramid_session_redis/blob/c65f7c2c45f1d13baebd75dce6798c11096d1776/pyramid_session_redis/util.py#L145-L164) in the source code.

> Is it true that pyramid_session_redis, the remember() cannot take a max_age keyword,

There is no `remember()` in this package, so I don't know how to answer that.

It sounds like you're trying to do a few things that are somewhat incompatible:

1- Have a login cookie for 1 year
2- Store CSRF data in a cookie for 1800 seconds
3- Have a cookie for 10 years

These things aren't really compatible with this package, it's predecessor, or anything that uses the Pyramid session interface.  When using the Pyramid session interface (i.e. any library that implements `[ISession](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/interfaces.html#pyramid.interfaces.ISession)` and binds it to `request.session`), we're tied to a single cookie -- unless another session is mapped onto the request.  So we need to be a bit creative on settings (which is where there are so many options here) or add-on extra sessions/cookies (which can be much easier at times!).

In terms of the settings you want...

`cookie_max_age` is passed on to `WebOb.response.Response.set_cookie` as `max_age`, and is used to tell the browser how long the cookie should be stored. `None` is a browser-session scope (cookie dies when the app dies), and any value is in seconds.  There is no reason to set this to 10 years.  It should max out at 1 year, because you want to "allow logged in users 1 years".

`timeout` should be `1800`, so you have your logged-out quick expiry.

Using `adjust_timeout_for_session` to extend the timeout like that is correct.  It changes the internal payload's timeout, which will then be set in redis when the cookie persists.  It is decorated with a `@persist` marker, so the new value will be set when invoked.

`timeout = 31536000 with timeout_trigger = 900 doesn't really make any sense, does it?`

Yes and no.  All this value does, is delay updating the SETEX until the cookie is at least 900 seconds old.  For logged-out users this can be very useful -- it guards against spiders/bots and helps empty out the Redis LRU sooner. For logged-in users, it's not going to have much of an impact.

I strongly suggest against a 1 year server-side session cookie though. I don't think they should be expected to last more than a few weeks - as you can end up with so many abandoned server sessions that eat at Redis and system resources.  The devops work and downtime to get around these situations is a nightmare.

When I was in a situation like yours, I opted for a short session cookie PLUS a long-term client-side encrypted 'autologin' cookie.  if someone is logged out, I check the headers for the encrypted client-side cookie and log them back into a new session.  If Redis has issues, or we have to put it into a LRU mode and lose the user's cookie, they have no idea because the autologin cookie self-heals their experience by creating a new session.

**Comment by hyperknot** [comment]
Thanks for the detailed answer and sorry for the later reply.

> First- timeout_trigger is a feature that you may not need. 

It's probably the case. With the old module I served 1 million requests per day just fine, and that was with the un-optimised code which added a redis lookup on _every_ request. The new code is way better, only adding a lookup when it's actually needed, so I'm perfectly happy not to use timeout_trigger.

> There is no remember() in this package, so I don't know how to answer that.

In the Pyramid documentation [1](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/authentication.html#pyramid.authentication.AuthTktAuthenticationPolicy.remember) and [2](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/security.html#pyramid.security.remember) remember supports max_age. So what does that do? (I know if it's not in this package I should be asking this on Pyramid mailing list, which I will do).

> I strongly suggest against a 1 year server-side session cookie though.

But what is the problem with that? I have 90k users and the redis dump is 21 MB, redis-server is using 115 MB of memory. That's basically the lightest process of the webserver.

> When I was in a situation like yours, I opted for a short session cookie PLUS a long-term client-side encrypted 'autologin' cookie.

That's probably the best solution, but for my case it would be over-engineering. I basically want to replicate the user experience of Facebook for example, where if someone logs in, they are never ever logged out, unless clicking logging out. Websites which log users out for no reason are not user friendly in my opinion.

**Comment by jvanasco** [comment]
> I have 90k users and the redis dump is 21 MB, redis-server is using 115 MB of memory. That's basically the lightest process of the webserver.

Once I had a bunch of spiders hit a site with (these) server side sessions. The spiders weren’t session-aware (or didn’t care) and pretty much triggered a new session each request from the csrf functionality.  This maxed out redis, which was capped at 400mb.  The usual load was 40mb.  I switched the cache to be LRU and evict older data to keep running, but that just effectively killed actual user’s sessions.

The easiest fix to ensure the “persistent login” UX like Facebook/Twitter/etc was to use a secondary Autologin cookie.  It was super simple to implement in a pyramid tween.  I just check for a login cookie, and if it fails.,. Follow up with an autologin cookie check; which re-establishes a server side session behind the scenes.

I don’t worry much about redis losing sessions anymore.  The app self-heals and the users have no idea, because their UX is seamless.

I think this took about 2 hours to write, and another 3-4 to tweak.  I lost way more than that dealing with all the mess after the spiders hit.

**Comment by hyperknot** [comment]
Just for reference I'd like to post what worked for me. Thanks for the detailed help.

Finally I've settled on the following values:
```
redis.sessions.secret = xxx
redis.sessions.cookie_max_age = 315360000   # 10 years, basically forever
redis.sessions.timeout = 1800
redis.sessions.cookie_secure = True
redis.sessions.cookie_httponly = True
redis.sessions.cookie_samesite = lax
```

login:
```
headers = remember(request, user.id)

redis_timeout = 3600 * 24 * 365  # one year in Redis
request.session.adjust_timeout_for_session(redis_timeout)

return HTTPFound(location=next, headers=headers)
```

I've thought about it and analyzed it and come up with the solution that this will work well for my usecase. I've never experienced any problem with the previous version of the library with similar values, which have created way more sessions then this one, as this only creates a session when it's actually needed on a login/registration page, leaving home page, etc. session-less.

**Comment by jvanasco** [comment]
`1.6` is now live on Github and PyPi.

It is backwards compatible with 1.5 and Python 1.x.

Two new methods are introduced to ``Session``:

* `Session.adjust_cookie_expires`
* `Session.adjust_cookie_max_age`
